import './globals.css'
import Providers from './store/provider'
import  Inter  from 'next/font/google'
import Header from './Layout/Header'




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >

      <Providers>
      {/* <Header/> */}
        <main className='px-8 md:px-28'>{children}</main></Providers>
      </body>
    </html>
  )
}
